version: '3'
services:
    web:
        image: jakubboucek/lamp-devstack-php
        volumes:
            - ".:/var/www/html"
        ports:
            - "127.0.0.1:8080:80"
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        image: jakubboucek/lamp-devstack-mysql
        restart: always
        environment:
            MYSQL_DATABASE: default
            MYSQL_ROOT_PASSWORD: devstack
        ports:
            - "127.0.0.1:33060:3306"
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
