services:
    web:
        image: jakubboucek/lamp-devstack-php:debug
        environment:
            # APACHE_DOCUMENT_ROOT: "/var/www/html/www"
            APP_DEBUG: 1
            TZ: Europe/Prague
            # PHP_IDE_CONFIG: "serverName=docker-cli"
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        ports:
            - "127.0.0.1:8080:80"
        restart: always
        volumes:
            - ".:/var/www/html"

    mysqldb:
        image: jakubboucek/lamp-devstack-mysql
        environment:
            MARIADB_DATABASE: default
            MARIADB_ROOT_PASSWORD: devstack
            TZ: Europe/Prague
        ports:
            - "127.0.0.1:33060:3306"
        restart: always
        volumes:
            - "./.docker/mysql/data:/var/lib/mysql"
